DROP DATABASE IF EXISTS uni4life;
CREATE DATABASE uni4life;

USE uni4life;

CREATE TABLE USUARIOS(
	ID_USUARIO VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY DEFAULT (uuid()),
	NOME VARCHAR(255),
	EMAIL VARCHAR(255),
	SENHA VARCHAR(255),
    REGISTRO_ACADEMICO VARCHAR(255),
	TIPO_CONTA VARCHAR(255),
	TELEFONE VARCHAR(255),
    QUANTIDADE_SEGUIDORES BIGINT,
	IMAGEM_USUARIO VARCHAR(255),
	DATA_NASCIMENTO DATE,
	SEGMENTO VARCHAR(255)
);

CREATE TABLE SEGUIDORES(
	ID_SEGUIDO_SEGUIDOR VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY DEFAULT (uuid()),
	ID_SEGUIDO VARCHAR(255),
    ID_SEGUIDOR VARCHAR(255),
    DATA_INICIO_RELACIONAMENTO DATETIME,
	FOREIGN KEY (ID_SEGUIDO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_SEGUIDOR) REFERENCES USUARIOS(ID_USUARIO)
);

-- INSERT INTO USUARIOS (NOME, EMAIL, SENHA, TIPO_CONTA, TELEFONE, DATA_NASCIMENTO, SEGMENTO) VALUES ("Luan", "luangenro@gmail.com", "123", "Admin", "51997921312", now(), "A");

CREATE TABLE EVENTOS(
    ID_EVENTO VARCHAR(50) NOT NULL PRIMARY KEY DEFAULT (uuid()),
    DESCRICAO VARCHAR(255),
    DATA_CRIACAO DATETIME,
    NOTIFICACAO_ENVIADA BOOL,
    ID_USUARIO VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- INSERT INTO EVENTOS (DESCRICAO, DATA_CRIACAO, NOTIFICACAO_ENVIADA, ID_USUARIO) VALUES ("Liked a post", now(), true, (SELECT ID_USUARIO FROM USUARIOS WHERE NOME = "Luan"));

CREATE TABLE CONTEUDOS(
	ID_CONTEUDO VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY DEFAULT (uuid()),
	TITULO VARCHAR(255),
	DESCRICAO VARCHAR(2000),
	TIPO_CONTEUDO VARCHAR(255),
	LINK_CONTEUDO VARCHAR(255),
	DATA_CRIACAO DATETIME,
	DATA_ATUALIZACAO DATETIME,
    IMAGEM_CONTEUDO VARCHAR(255),
    ID_USUARIO VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- INSERT INTO CONTEUDOS (TITULO, DESCRICAO, TIPO_CONTEUDO, LINK_CONTEUDO, DATA_CRIACAO, DATA_ATUALIZACAO, ID_USUARIO) VALUES ("Foto do dog", "Mais um dia com o meu melhor amigo", "Picture", "link", now(), now(), (SELECT ID_USUARIO FROM USUARIOS WHERE NOME = "Luan"));

CREATE TABLE FAVORITOS (
	ID_FAVORITO VARCHAR(50) NOT NULL PRIMARY KEY DEFAULT (uuid()),
	DATA_CRIACAO DATETIME,
	ID_USUARIO VARCHAR(50),
	ID_CONTEUDO VARCHAR(50),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDOS(ID_CONTEUDO)
);

-- INSERT INTO FAVORITOS(DATA_CRIACAO, ID_USUARIO, ID_CONTEUDO) VALUES (now(), (SELECT ID_USUARIO FROM USUARIOS WHERE NOME = "Luan"), (SELECT ID_CONTEUDO FROM CONTEUDOS WHERE TITULO = "Foto do dog"));

CREATE TABLE GOSTEIS (
    ID_GOSTEI VARCHAR(50) NOT NULL PRIMARY KEY DEFAULT (uuid()),
    TITULO VARCHAR(255),
    DATA_CRIACAO DATETIME,
    ID_USUARIO VARCHAR(50),
    ID_CONTEUDO VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDOS(ID_CONTEUDO)
);

-- INSERT INTO GOSTEIS(TITULO, DATA_CRIACAO, ID_USUARIO, ID_CONTEUDO) VALUES ("Like 1", now(), (SELECT ID_USUARIO FROM USUARIOS WHERE NOME = "Luan"), (SELECT ID_CONTEUDO FROM CONTEUDOS WHERE TITULO = "Foto do dog"));

CREATE TABLE COMENTARIOS(
    ID_COMENTARIOS VARCHAR(50) NOT NULL PRIMARY KEY DEFAULT (uuid()),
    TITULO VARCHAR(255),
    DESCRICAO VARCHAR(255),
    DATA_CRIACAO DATETIME,
    DATA_ATUALIZACAO DATETIME,
    ID_USUARIO VARCHAR(50),
    ID_CONTEUDO VARCHAR(50),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDOS(ID_CONTEUDO)
);

-- INSERT INTO COMENTARIOS(TITULO, DESCRICAO, DATA_CRIACAO, DATA_ATUALIZACAO, ID_USUARIO, ID_CONTEUDO) VALUES ("Comment 1", "Meu dog é mt charmoso!", now(), now(), (SELECT ID_USUARIO FROM USUARIOS WHERE NOME = "Luan"), (SELECT ID_CONTEUDO FROM CONTEUDOS WHERE TITULO = "Foto do dog"));