spring:
  h2:
    console:
      enabled: true
      path: /banco
      settings:
        trace: false
        web-allow-others: true
  datasource:
    continue-on-error: true
    driverClassName: org.h2.Driver
    username: ${BD_USERNAME:root}
    password: ${BD_PASSWORD:root}
    url: jdbc:h2:mem:uni4life
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create